# version: "3.9"

services:
  jobtracker-backend:
    image: jobtracker-backend
    environment:
      - MONGO_URI=mongodb://jobtracker-mongo:27017/jobtracker
    networks:
      - jobtracker-net
    ports:
      - 5000:5000
    depends_on:
      - jobtracker-mongo

  jobtracker-mongo:
    image: mongo:6
    networks:
      - jobtracker-net
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

networks:
  jobtracker-net:
    external: true

volumes:
  mongo_data:
    external: true
